Integrate redeem code system
DGP-Studio/Snap.Hutao.Server pull request #64
Opened 2024-12-29 12:35 UTC by qhy040404

2024-12-30 05:34 UTC, Lightczx commented
增加兑换码限时，通用兑换码（限制兑换次数）

2024-12-30 13:01 UTC, Lightczx requested changes

2024-12-31 06:37 UTC, Masterain98 commented
@ai-review

2024-12-31 06:46 UTC, Masterain98 commented
/pr-summary

2025-01-02 02:31 UTC, Lightczx requested changes

2025-01-02 02:31 UTC, Lightczx commented on src/Snap.Hutao.Server/Snap.Hutao.Server/Model/Entity/Redeem/RedeemCode.cs
> +    public bool IsUsed { get; set; }
Should we add another table RedeemCodeUseItem?

2025-01-02 02:31 UTC, Lightczx commented on src/Snap.Hutao.Server/Snap.Hutao.Server/Model/Redeem/RedeemGenerateRequest.cs
> +    [JsonPropertyName("n")]
remove or rename JsonPropertyName

2025-01-02 08:35 UTC, Lightczx approved these changes

2025-01-02 08:35 UTC, merged